### ISSUE TITLE
How are we storing the data?

### ISSUE THREAD

**Issue by nrgill28** [FRC2706/mergserv#1]
Will we be using a database such as MySQL or will we be saving all the data as files?

**Comment by crabctrl** [comment]
We are using a MySQL database as describe in the Google Doc with the completely ridiculous name. I'll post the list here for future reference:

- Events table
    - Insert time
    - Type
    - Team
    - Match
    - Start time
    - End time
    - Success
    - Extra
    - Scout name
    - Scout team

- Matches table
    - Matchnum
    - Competition
    - Blue 1
    - Blue 2
    - Blue 3
    - Red 1
    - Red 2
    - Red 3
    - Final blue score
    - Final red score

- Competitions table
    - Name
    - Year
    - Location

- Scouts table
    - Name
    - Team number
    - Time registered
    - Team signature

- Teams table
    - Team number
    - Name

- Team identification table
    - Team number
    - Public key
    - Signature

- Purchases table
    - Matches
    - Name
    - Cost
    - Timestamp
    - Signature

**Comment by kevlam2706** [comment]
On a housekeeping note, currently your scouting app/server designs are
still being saved to the 2017/2018 folder in our team Google Drive. We
have a new folder for 2018/2019 software work, and we should copy or
move the scouting stuff over there.

**Comment by crabctrl** [comment]
Database code is finished; we are using Sqlite. Google Doc is being deleted.
