### ISSUE TITLE
How are we transfering the data?

### ISSUE THREAD

**Issue by nrgill28** [FRC2706/mergserv#2]
Are we using a binary protocol (such as BSON) or an ASCII protocol (such as JSON)?

**Comment by crabctrl** [comment]
- [ ] pull(last_update_time)
   - Download events from a given match which were inserted into the database after a certain time
- [ ] push(events)
    - Pushes events to another peer
- [ ] dump_competition(competition)
    - Dumps all matches for the given competition
- [ ] list_competitions(year)
    - Lists all competitions for this year
- [ ] push_scores(hashmap<matchid, [scorered, scoreblue]>)
    - Pushes the final scores for some matches, which is fetched by the server by TBA
    - If the device already has scores for a given match, the scores are not updated
- [ ] pull_scores(competition, last match with scores)

**Comment by crabctrl** [comment]
So the decision is that we're using normal JSON. We should split this up into new issues now, one for each API call
