### ISSUE TITLE
Read commands from stdin

### ISSUE THREAD

**Issue by crabctrl** [FRC2706/mergserv#26]
This depends on #17, and would allow other programs (eg apps) as well a programmers trying to debug this mess to issue requests

**Comment by nrgill28** [comment]
What kind of commands do we want to include? I made a branch and made some changes to the code (7d627d3) to allow stdin on the main thread

**Comment by crabctrl** [comment]
We need a command to push a sync to all of ours peers, and a command to insert events into the database. We possibly want to be able to enable/disable networking, so the Android app can turn off networking if on cell data

**Comment by crabctrl** [comment]
Actually wait screw that, we don't need a command to insert into the database; just one to do a sync

**Comment by nrgill28** [comment]
There's now commands to enable/disable networking (f94e917), disabling network will stop the server from listening and accepting new connections. I'm not sure how to do the peer sync part though
